### ISSUE TITLE
GUI not connected

### ISSUE THREAD

**Issue by okuemmel** [spocon/lovspotify#1]
Hi, i always get 'Spotify not connected' on the webside. Tried different auth methods but no changes..
Connection and playing works, only a Gui topic
any hints?

Greets
Oliver

**Comment by spocon** [comment]
interesting, could you double check that you are really connected with the right device : "Lovspotify" ? 

![2020-03-22 13_06_22-Spotify Premium](https://user-images.githubusercontent.com/52956690/77248967-112aa100-6c3e-11ea-8321-28fee82ceb87.png)

Any other spotify clients connected ? raspotify or spocon ?
Do you have any Adblockers active ?
Which browser are you using ? 

When you press F12 ( developer tools ) in your browser and check network  are there calls towards localhost:8080/player/current ?

**Comment by okuemmel** [comment]
Hi 
yes connection is right (raspotify is un installed ;-) ), Im using Crome @Ubuntu tried also firefox!


![image](https://user-images.githubusercontent.com/54982883/77249342-9911aa80-6c40-11ea-9066-edd37011e895.png)

WTF.... is localhost hardcoded? 
no access from remote?

**Comment by spocon** [comment]
yes its always localhost:8080 which than connects over a REST API with the backbone of librespot-core. It uses a zeroconf server which connects with your wifi or LAN.

Could you open a terminal and give me the output of : 
`curl localhost:8080/player/current
`

**Comment by spocon** [comment]
which version of ubuntu are you using ? 
Any firewall entries ?
It could be also helpful to see the logs from lovspotify
you can get them by : 

`journalctl --no-pager -u lovspotify`

also : 

`service lovspotify status`

**Comment by okuemmel** [comment]
ok, step by step...
luvspotify is runing in at a raspberry with actual rasbian .
curl output: 
```
pi@raspberrypi:~ $ curl localhost:8080/player/current
pi@raspberrypi:~ $ curl localhost:8080
<html lang="en">

<head>

    <title>Spotify Client</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" href="3rd-party/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="3rd-party/bootstrap/4.3.1/js/bootstrap.bundle.js"></script>
    <script src="3rd-party/jquery/jquery-3.4.1.min.js"></script>
    <script src="js/general.js"></script>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-text" href="#">
            <h3>SpoCon - (Spotify Client Connector)</h3>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" target="_blank" href="https://github.com/spocon/lovspotify">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container bg-light p-lg-3">
    <div class="row justify-content-center">
        <div id="spotify-not-connected" class="alert alert-primary w-100 text-center" role="alert">
            Spotify not connected
        </div>
    </div>
    <div class="row justify-content-center">
        <div>
            <img alt="spotify-image" style="width: 300px; height: 300px" src="" id="spotify-image"/>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="row bg-dark justify-content-center" style="width: 300px">
            <div>
                <button class="btn btn-dark" onclick="song_backward()"><i class="fa fa-backward fa-3x "></i>
                </button>
            </div>
            <div>
                <button id="play_pause_button" class="btn btn-dark" onclick="song_pause()"><i id="play_pause_image"
                                                                                              class="fa fa-pause fa-3x"></i>
                </button>
            </div>
            <div>
                <button class="btn btn-dark" onkeypress="" onclick="song_forward()"><i class="fa fa-forward fa-3x"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="pl-md-3 pt-2">
        <div class="row">
            <div id="head-artist" class="col-2 h3">Artist:</div>
            <div class="h3" id="spotify-artist"></div>
        </div>
        <div class="row">
            <div id="head-song" class="col-2 h3">Song:</div>
            <div class="h3" id="spotify-title"></div>
        </div>
        <div class="h6 pl-3 pt-4 float-left">
            <div class="row">
                <p>Last Song: </p><p class="ml-3 mr-3 fa fa-arrow-left btn btn-dark"></p>
                <p>Next Song: </p><p class="ml-3 mr-3 fa fa-arrow-right btn btn-dark"></p>
                <p>Volume Up: </p><p class="ml-3 mr-3 fa fa-arrow-up btn btn-dark"></p>
                <p>Volume Down: </p><p class="ml-3 mr-3 fa fa-arrow-down btn btn-dark"></p>
            </div>
        </div>
    </div>

</div>
</body>

pi@raspberrypi:~ $ 

```

**Comment by okuemmel** [comment]
> which version of ubuntu are you using ?
> Any firewall entries ?
> It could be also helpful to see the logs from lovspotify
> you can get them by :
> 
> `journalctl --no-pager -u lovspotify`
> 
> also :
> 
> `service lovspotify status`

``Mar 22 12:33:49 raspberrypi sh[396]: rtt min/avg/max/mdev = 10.591/10.591/10.591/0.000 ms
Mar 22 12:33:49 raspberrypi systemd[1]: Started lovspotify.
Mar 22 12:34:24 raspberrypi java[837]:   .   ____          _            __ _ _
Mar 22 12:34:24 raspberrypi java[837]:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
Mar 22 12:34:24 raspberrypi java[837]: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
Mar 22 12:34:24 raspberrypi java[837]:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
Mar 22 12:34:24 raspberrypi java[837]:   '  |____| .__|_| |_|_| |_\__, | / / / /
Mar 22 12:34:24 raspberrypi java[837]:  =========|_|==============|___/=/_/_/_/
Mar 22 12:34:24 raspberrypi java[837]:  :: Spring Boot ::        (v2.2.5.RELEASE)
Mar 22 12:34:26 raspberrypi java[837]: 2020-03-22 12:34:26.803  INFO 837 --- [           main] m.h.l.s.SpotifiApplication               : Starting SpotifiApplication on raspberrypi with PID 837 (/opt/lovspotify/lovspotify-1.0.1.jar started by lovspotify in /opt/lovspotify)
Mar 22 12:34:26 raspberrypi java[837]: 2020-03-22 12:34:26.943  INFO 837 --- [           main] m.h.l.s.SpotifiApplication               : No active profile set, falling back to default profiles: default
Mar 22 12:34:41 raspberrypi java[837]: 2020-03-22 12:34:41.670  INFO 837 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat initialized with port(s): 8080 (http)
Mar 22 12:34:41 raspberrypi java[837]: Mar 22, 2020 12:34:41 PM org.apache.coyote.AbstractProtocol init
Mar 22 12:34:41 raspberrypi java[837]: INFO: Initializing ProtocolHandler ["http-nio-8080"]
Mar 22 12:34:41 raspberrypi java[837]: Mar 22, 2020 12:34:41 PM org.apache.catalina.core.StandardService startInternal
Mar 22 12:34:41 raspberrypi java[837]: INFO: Starting service [Tomcat]
Mar 22 12:34:41 raspberrypi java[837]: Mar 22, 2020 12:34:41 PM org.apache.catalina.core.StandardEngine startInternal
Mar 22 12:34:41 raspberrypi java[837]: INFO: Starting Servlet engine: [Apache Tomcat/9.0.31]
Mar 22 12:34:42 raspberrypi java[837]: Mar 22, 2020 12:34:42 PM org.apache.catalina.core.ApplicationContext log
Mar 22 12:34:42 raspberrypi java[837]: INFO: Initializing Spring embedded WebApplicationContext
Mar 22 12:34:42 raspberrypi java[837]: 2020-03-22 12:34:42.881  INFO 837 --- [           main] o.s.w.c.ContextLoader                    : Root WebApplicationContext: initialization completed in 15305 ms
Mar 22 12:34:44 raspberrypi java[837]: 2020-03-22 12:34:44 INFO  Utils:73 - Cryptography restrictions removal not needed.
Mar 22 12:34:44 raspberrypi java[837]: 2020-03-22 12:34:44 INFO  ApResolver:66 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-b-gxtv.ap.spotify.com:4070, gew1-accesspoint-b-7825.ap.spotify.com:443, gew1-accesspoint-b-2jfx.ap.spotify.com:80, gew1-accesspoint-b-zv92.ap.spotify.com:4070, gew1-accesspoint-b-vlpq.ap.spotify.com:443, gew1-accesspoint-b-f6mh.ap.spotify.com:80, gae2-accesspoint-b-m87x.ap.spotify.com:4070, gae2-accesspoint-b-0fvt.ap.spotify.com:443, guc3-accesspoint-b-37ks.ap.spotify.com:80], dealer=[gew-dealer.spotify.com:443, guc-dealer.spotify.com:443, gae-dealer.spotify.com:443], spclient=[gew-spclient.spotify.com:443, guc-spclient.spotify.com:443, gae-spclient.spotify.com:443]}
Mar 22 12:34:45 raspberrypi java[837]: 2020-03-22 12:34:45 INFO  ZeroconfServer:369 - Zeroconf HTTP server started successfully on port 5588!
Mar 22 12:34:46 raspberrypi java[837]: 2020-03-22 12:34:46 INFO  Zeroconf:456 - Announced service: Service{alias='Lovspotify', service='spotify-connect', port=5588, text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/192.168.100.42], domain='.local', protocol='tcp', host='raspberrypi'}
Mar 22 12:34:48 raspberrypi java[837]: 2020-03-22 12:34:48.841  INFO 837 --- [           main] o.s.s.c.ThreadPoolTaskExecutor           : Initializing ExecutorService 'applicationTaskExecutor'
Mar 22 12:34:50 raspberrypi java[837]: 2020-03-22 12:34:50.183  INFO 837 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
Mar 22 12:34:51 raspberrypi java[837]: Mar 22, 2020 12:34:51 PM org.apache.coyote.AbstractProtocol start
Mar 22 12:34:51 raspberrypi java[837]: INFO: Starting ProtocolHandler ["http-nio-8080"]
Mar 22 12:34:51 raspberrypi java[837]: 2020-03-22 12:34:51.972  INFO 837 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat started on port(s): 8080 (http) with context path ''
Mar 22 12:34:52 raspberrypi java[837]: 2020-03-22 12:34:52.010  INFO 837 --- [           main] m.h.l.s.SpotifiApplication               : Started SpotifiApplication in 33.8 seconds (JVM running for 50.311)
Mar 22 12:42:05 raspberrypi java[837]: Mar 22, 2020 12:42:05 PM org.apache.catalina.core.ApplicationContext log
Mar 22 12:42:05 raspberrypi java[837]: INFO: Initializing Spring DispatcherServlet 'dispatcherServlet'
Mar 22 12:42:05 raspberrypi java[837]: 2020-03-22 12:42:05.303  INFO 837 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Initializing Servlet 'dispatcherServlet'
Mar 22 12:42:05 raspberrypi java[837]: 2020-03-22 12:42:05.413  INFO 837 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Completed initialization in 105 ms
pi@raspberrypi:~ $ 
```

```
pi@raspberrypi:~ $ sudo service lovspotify status
● lovspotify.service - lovspotify
   Loaded: loaded (/lib/systemd/system/lovspotify.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-22 12:33:49 GMT; 22min ago
 Main PID: 837 (java)
    Tasks: 29 (limit: 2200)
   Memory: 119.8M
   CGroup: /system.slice/lovspotify.service
           └─837 /usr/bin/java -jar /opt/lovspotify/lovspotify-1.0.1.jar --conf-file=/opt/lovspotify/config.toml

Mar 22 12:34:48 raspberrypi java[837]: 2020-03-22 12:34:48.841  INFO 837 --- [           main] o.s.s.c.ThreadPoolTaskExecutor           : Initializing ExecutorService 'applicationTaskExecutor'
Mar 22 12:34:50 raspberrypi java[837]: 2020-03-22 12:34:50.183  INFO 837 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html
Mar 22 12:34:51 raspberrypi java[837]: Mar 22, 2020 12:34:51 PM org.apache.coyote.AbstractProtocol start
Mar 22 12:34:51 raspberrypi java[837]: INFO: Starting ProtocolHandler ["http-nio-8080"]
Mar 22 12:34:51 raspberrypi java[837]: 2020-03-22 12:34:51.972  INFO 837 --- [           main] o.s.b.w.e.t.TomcatWebServer              : Tomcat started on port(s): 8080 (http) with context path ''
Mar 22 12:34:52 raspberrypi java[837]: 2020-03-22 12:34:52.010  INFO 837 --- [           main] m.h.l.s.SpotifiApplication               : Started SpotifiApplication in 33.8 seconds (JVM running for
Mar 22 12:42:05 raspberrypi java[837]: Mar 22, 2020 12:42:05 PM org.apache.catalina.core.ApplicationContext log
Mar 22 12:42:05 raspberrypi java[837]: INFO: Initializing Spring DispatcherServlet 'dispatcherServlet'
Mar 22 12:42:05 raspberrypi java[837]: 2020-03-22 12:42:05.303  INFO 837 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Initializing Servlet 'dispatcherServlet'
Mar 22 12:42:05 raspberrypi java[837]: 2020-03-22 12:42:05.413  INFO 837 --- [nio-8080-exec-1] o.s.w.s.DispatcherServlet                : Completed initialization in 105 ms
```

**Comment by okuemmel** [comment]
same behaviour at raspberry , just installed x11 and chromium for verification

**Comment by spocon** [comment]
im running it on a raspberry pi 3 with Raspbian installed on chromiumm. Dont have any issues. but let me come back to you after i have tested it with a fresh version

**Comment by spocon** [comment]
I removed and installed version Lovspotify 1.0.1 on my Raspbian and it worked as expected. even if im not connected with the client i get by calling /player/current the response 404 ( not found ) and not 500 back.  Also there is no OPTIONS method blocked.  

Are you accessing Lovspotify directly over a connected Monitor where it is installed ?

The only thing what could happen is that something happend during the installation. I would recommend to uninstall everything. 

`apt remove --purge lovspotify`

check that this is not there anymore 
`
ls -la /lib/systemd/system/lovspotify.service
ls -la /opt/lovspotify
`
and reinstall: 
`
curl -sL https://spocon.github.io/spocon/script/install_lovspotify.sh | sh
`

**Comment by spocon** [comment]
I will soon release a new version with removing the hardcoded localhost in the frontend. Than it should be possible to reach the Lovspotify GUI over the ip from any computer in the network

**Comment by spocon** [comment]
Release 1.0.2 is created and send to launchpad . They need usually 30 - 60 min until its published. 

its possible to change the port of the GUI now . its under /opt/lovspotify/gui.yml after you installed the new version

upgrade : 
`apt update && apt upgrade -y`

**Comment by okuemmel** [comment]
Great, getting better. 
connection works , cover and title also. Buttons below the cover are working, but the Buttons last/next song and Volume up/down are not working... ;-)

**Comment by spocon** [comment]
these are no buttons to click on , its actually meant to use with the keyboard :-) but I probably write that to them ;-)

**Comment by spocon** [comment]
I think we can close this one .
