### ISSUE TITLE
Volume varies between the Tracks

### ISSUE THREAD

**Issue by FritzeF** [spocon/lovspotify#10]
Hello,

the volume varies extrem between the Tracks.
Some tracks are very quite some are so loud that my speakers oversteers.
A change in the settings from Spotify connect app "equal volume for each tracks" results in no change.

Lovespotify runs on a Pi4 under actual raspbian.

**Comment by thorstenhaga-tradedoubler** [comment]
which version are you running ?

**Comment by FritzeF** [comment]
Pi4:
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

ii  lovspotify                            1.5.0                                  armhf        Spotify Connect for linux with librespot-java

Spotify App on Android 10: 8.5.71.723

**Comment by spocon** [comment]
There was a major change in librespot-java between 1.4.0 and 1.5.0 . Maybe thats a factor. Have you recognized the issue in 1.4.0 as well ?

**Comment by FritzeF** [comment]
No, because I installed lovspotify only a few days ago and the issue was there from the beginning.

**Comment by spocon** [comment]
Release 1.5.1 could fix your problem. its currently deploying , but it should be reachable in approx. 30 min 
There are some changes in the config.toml which could be intresting for your problem , please see the release notes for more informations
https://github.com/spocon/lovspotify/releases/tag/1.5.1 

If it doesn't fix it you should consider to open a issue in the project librespot-java

**Comment by FritzeF** [comment]
No, that update did not fixed my problem.
