### ISSUE TITLE
Loud and messy sound when switching to the next track

### ISSUE THREAD

**Issue by GraphGiraffe** [spocon/lovspotify#12]
Sometimes, when automatically skipping to the next track, the volume rises and the sound becomes messy.
But when I switch to another track and switch back, the sound is normal.

I have this issue on RPi4 on several OS: Twister OS, Raspberry Pi OS (64-bit), pi-topOS.
Lovspotify ver: 1.5.2

**Comment by siccl** [comment]
same issue
Linux ubuntu 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
lovspotify-1.5.2
Raspberry Pi 4 Model B Rev 1.2

**Comment by siccl** [comment]
> same issue
> Linux ubuntu 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
> lovspotify-1.5.2
> Raspberry Pi 4 Model B Rev 1.2
Logs : 
WARN  NormalizationData:52 - Reducing normalisation factor to prevent clipping. Please add negative pregain to avoid.

**Comment by spocon** [comment]
Seems to be related to this issue:
https://github.com/librespot-org/librespot-java/issues/199#issue-595749392

**Comment by siccl** [comment]
i think something on your comment (tying -3)
change volume (initialVolume = 49152)
alsamixer volume down from 100% to 80%
on mayor values to normalisationPregain some songs keep in silent

**Comment by spocon** [comment]
what do you have in  in player config ? 

[player] ### Player ###
.....
normalisationPregain = +3.0 # Normalisation pregain in decibels (loud at +6, normal at +3, quiet at -5)
......

+3.0 should do the trick , but these are configuretions from the underlying package librespot-java... i have no influence on this 

If you have still problems , please open a ticket in librespot-java 

Please check your configuration if there is a difference between the default : 

https://github.com/spocon/lovspotify/blob/master/src/main/resources/config.toml

**Comment by spocon** [comment]
Probably related to this one as well:

https://github.com/spocon/lovspotify/issues/13#issuecomment-701560998
