### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by maxbenkert** [spocon/lovspotify#14]
Hi,
lovspotify suddenly stopped working.

Dec 25 21:20:14 hostname java[15543]: 2020-12-25 21:20:14,904 INFO  ZeroconfServer:327 - Accepted new user from DESKTOP-5VQ5LT7. {deviceId: 53f8fa0>
Dec 25 21:20:15 hostname java[15543]: 2020-12-25 21:20:15,372 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-b-lhnn.ap.>
Dec 25 21:20:17 hostname java[15543]: 2020-12-25 21:20:17,103 INFO  Session:122 - Created new session! {deviceId: _randomid_>
Dec 25 21:20:17 hostname java[15543]: 2020-12-25 21:20:17,923 INFO  Session:313 - Connected successfully!
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,249 INFO  CacheManager:80 - There are 0 cached entries.
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,279 INFO  Session:1375 - Skipping SecretBlock
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,283 INFO  Session:1347 - Received LicenseVersion: 0
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,285 INFO  Session:1337 - Received CountryCode: DE
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,415 INFO  Session:1375 - Skipping LegacyWelcome
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,418 INFO  Session:1375 - Skipping UnknownData_AllZeros
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,423 INFO  Session:1302 - Skipping unknown command {cmd: 0x75, payload: 000000}
Dec 25 21:20:18 hostname java[15543]: 2020-12-25 21:20:18,592 INFO  Session:344 - Authenticated as _username_!
Dec 25 21:20:20 hostname java[15543]: 2020-12-25 21:20:20,267 INFO  StateWrapper:300 - Notified new device (us)!
Dec 25 21:20:20 hostname java[15543]: 2020-12-25 21:20:20,992 INFO  DeviceStateHandler:252 - Put state. {ts: 1608927620244, connId: NTNmO...yRTFC, >
lines 1-26/26 (END)

If I start to play on another device (such as an Amazon Echo) and switch then to lovspotify, it works.
I recently updated to the newest release.

Raspberry Pi 3
Ubuntu 20.04

**Comment by spocon** [comment]
Librespot has fixed the problem but haven't made a new release yet. https://github.com/librespot-org/librespot-java/issues/277

**Comment by timgoeller** [comment]
They just made the release :3 https://github.com/librespot-org/librespot-java/releases/tag/v1.5.3

**Comment by spocon** [comment]
Unfortunately not yet here : https://mvnrepository.com/artifact/xyz.gianlu.librespot/librespot-player maybe needs some time to go through publishing the artifact

**Comment by spocon** [comment]
@timgoeller @maxbenkert  the new version is currently "in building" it usually takes 1 or 2 hours until its published.

**Comment by timgoeller** [comment]
@spocon Seems to work like a charm for me!

**Comment by BeAddicted** [comment]
Somehow I don't think this bug has been fixed. I'm using the newest version 1.5.4 but the bug described above does still apply to me. Im trying to connect with my phone and after some time trying it stops. I can see an exception in the logs that occures when I try to connect. 

Jan 23 13:02:33 raspberrypi java[8277]: INFORMATION: Initializing Spring DispatcherServlet 'dispatcherServlet'
Jan 23 13:02:33 raspberrypi java[8277]: 2021-01-23 13:02:33,725 INFO  DispatcherServlet:525 - Initializing Servlet 'dispatcherServlet'
Jan 23 13:02:33 raspberrypi java[8277]: 2021-01-23 13:02:33,782 INFO  DispatcherServlet:547 - Completed initialization in 54 ms
Jan 23 13:02:50 raspberrypi java[8277]: 2021-01-23 13:02:50,218 INFO  ZeroconfServer:329 - Accepted new user from Mi Note 2. {deviceId: 10df9c78474c79d19b93dfe52e484085d08abad8}
Jan 23 13:02:50 raspberrypi java[8277]: 2021-01-23 13:02:50,673 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-e-6f5c.ap.spotify.com:4070, gew1-accesspoint-e-f433.ap.spotify.com:443, gew1-accesspoint-e-zg04.ap.spotify.com:80, gew1-accesspoint-e-3cx6.ap.spotify.com:4070, gew1-accesspoint-e-fsf3.ap.spotify.com:443, gew1-accesspoint-e-7hr4.ap.spotify.com:80, guc3-accesspoint-e-8fth.ap.spotify.com:4070, guc3-accesspoint-e-ph00.ap.spotify.com:443, guc3-accesspoint-e-cdxm.ap.spotify.com:80], dealer=[gew-dealer.spotify.com:443, guc-dealer.spotify.com:443, gae-dealer.spotify.com:443], spclient=[gew-spclient.spotify.com:443, guc-spclient.spotify.com:443, gae-spclient.spotify.com:443]}
Jan 23 13:02:52 raspberrypi java[8277]: 2021-01-23 13:02:52,087 INFO  Session:120 - Created new session! {deviceId: 10df9c78474c79d19b93dfe52e484085d08abad8, ap: gew1-accesspoint-e-6f5c.ap.spotify.com:4070, proxy: false}
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,054 INFO  Session:311 - Connected successfully!
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,440 INFO  CacheManager:80 - There are 1 cached entries.
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,473 INFO  Session:1363 - Skipping SecretBlock
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,475 INFO  Session:1335 - Received LicenseVersion: 0
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,478 INFO  Session:1325 - Received CountryCode: DE
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,553 INFO  Session:1363 - Skipping LegacyWelcome
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,555 INFO  Session:1363 - Skipping UnknownData_AllZeros
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,558 INFO  Session:1290 - Skipping unknown command {cmd: 0x75, payload: 000000}
Jan 23 13:02:53 raspberrypi java[8277]: 2021-01-23 13:02:53,689 INFO  Session:342 - Authenticated as _username_
Jan 23 13:02:55 raspberrypi java[8277]: 2021-01-23 13:02:55,595 INFO  StateWrapper:301 - Notified new device (us)!
Jan 23 13:02:56 raspberrypi java[8277]: 2021-01-23 13:02:56,554 INFO  DeviceStateHandler:252 - Put state. {ts: 1611403375574, connId: MTBkZ...1ODE2, reason: NEW_DEVICE}
Jan 23 13:02:58 raspberrypi java[8277]: 2021-01-23 13:02:58,095 ERROR DealerClient:112 - Failed handling request. {key: e99bdbcb-f61c-4856-83b9-46243df2c00f}
Jan 23 13:02:58 raspberrypi java[8277]: java.lang.UnsupportedOperationException: null
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.metadata.UnsupportedId.getGid(UnsupportedId.java:17) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.common.ProtoUtils.lambda$jsonToContextTrack$0(ProtoUtils.java:121) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextTrack(ProtoUtils.java:119) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextTracks(ProtoUtils.java:137) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextPage(ProtoUtils.java:148) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextPages(ProtoUtils.java:156) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.mercury.MercuryRequests$ResolvedContextWrapper.pages(MercuryRequests.java:142) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.PagesLoader.getPage(PagesLoader.java:95) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.PagesLoader.nextPage(PagesLoader.java:129) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.initializeFrom(StateWrapper.java:1071) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.StateWrapper.transfer(StateWrapper.java:476) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.Player.handleTransferState(Player.java:368) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.Player.command(Player.java:300) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-player-1.5.3.jar!/:1.5.3]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-lib-1.5.3.jar!/:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
Jan 23 13:02:58 raspberrypi java[8277]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Jan 23 13:04:44 raspberrypi java[8277]: 2021-01-23 13:04:44,232 INFO  StateWrapper:321 - Notified inactivity!
Jan 23 13:04:44 raspberrypi java[8277]: 2021-01-23 13:04:44,507 INFO  DeviceStateHandler:252 - Put state. {ts: 1611403484229, connId: MTBkZ...1ODE2, reason: BECAME_INACTIVE}

Seems like the workaround described above seems to work. When I boot up my pc and connect my phone to the pc spotify first and then to lovspotify it works. But still not optimal the optimal solution to boot up my pc every time. Could you look into this again?

I'm also using it on an raspy 3 like above
