### ISSUE TITLE
Lovspotify is visible but fails to connect

### ISSUE THREAD

**Issue by and-who** [spocon/lovspotify#16]
Lovspotify is running and visible in Spotify.
But if i try to connect, it Fails.
This is should be a Bug in librespot which should be fixed in the current Version.

**Solution:** Update librespot see https://github.com/librespot-org/librespot-java/issues/281

Service log:

> Apr 30 12:10:30 raspberrypi java[1516]: 2021-04-30 12:10:30,008 INFO  PlayerSession:53 - Created new session. {id: djb5cVdmNvDFGYKERkvDkw}
Apr 30 12:10:30 raspberrypi java[1516]: 2021-04-30 12:10:30,010 ERROR DealerClient:112 - Failed handling request. {key: f51cb3cc-95fd-41e2-bf31-921e2fcf1921}
Apr 30 12:10:30 raspberrypi java[1516]: java.lang.IllegalStateException: null
Apr 30 12:10:30 raspberrypi java[1516]:         at xyz.gianlu.librespot.player.StateWrapper.getCurrentPlayableOrThrow(StateWrapper.java:558) ~[librespot-player-1.5.3.jar!/:1.5.3]
Apr 30 12:10:30 raspberrypi java[1516]:         at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:254) ~[librespot-player-1.5.3.jar!/:1.5.3]
Apr 30 12:10:30 raspberrypi java[1516]:         at xyz.gianlu.librespot.player.Player.loadSession(Player.java:239) ~[librespot-player-1.5.3.jar!/:1.5.3]

PS: Thank for your awesome Work, im currently building a nice Theme if im finished I will send a Sceenshot annd a Link to the Repo

**Comment by spocon** [comment]
Hi, I will soon make an update from librespot. I inform you when I'm finished

**Comment by spocon** [comment]
release done : https://github.com/spocon/lovspotify/releases/tag/1.5.5

Closing the issue

**Comment by SpyrosRoum** [comment]
Is the release comment correct? You are saying to upgrade spocon but this is lovspotify. 
Running `sudo apt --only-upgrade install spocon` says that it is not installed and thus does not need an upgrade. Running the same command for lovspotify says that the latest version is 1.5.4..
I have already run `sudo apt update`
