### ISSUE TITLE
Latest version in the repos is 1.5.4

### ISSUE THREAD

**Issue by SpyrosRoum** [spocon/lovspotify#17]
Hello! I install lovspotify using the `curl | sh` script you provide while 1.5.4 version was out.
I want to update to the latest to solve issue #16 but I cannot since the latest version in the repos is still 1.5.4.

Am I missing something/doing something wrong here?

Edit to mention: I did run `sudo apt update` and I'm on a Raspberry Pi 4 with Raspbian

**Comment by spocon** [comment]
Hi SpyrosRoum,

this are the supported versions. you probably use the Bionic version when you executed the script. Its on version 1.6.0 . please update and upgrade your raspberry pi. 

![bild](https://user-images.githubusercontent.com/52956690/119238254-be9a8c80-bb41-11eb-9c73-6139a8710d54.png)

**Comment by spocon** [comment]
you can also download the deb package directly here:  https://launchpad.net/~spocon/+archive/ubuntu/lovspotify/+packages

**Comment by SpyrosRoum** [comment]
Sorry for the late reply, for some reason I didn't get a notification for this..
Anyway, I believe I do indeed use the Bionic version, I installed Rasbpian very recently 
I can see that the latest version is 1.6 from the link you sent but running `sudo apt update && sudo apt upgrade` still doesn't update lovspotify

> please update and upgrade your raspberry pi.

Does this mean something other than the command I wrote above?

**Comment by SpyrosRoum** [comment]
I had to run the installation script again (not sure why I didn't try that earlier) but at least it worked
