### ISSUE TITLE
Spotify shows Device not avaiable 

### ISSUE THREAD

**Issue by unbeeyt** [spocon/lovspotify#18]
So i have tried the programm and when i tried to use spotify to connect to lovspotify (every data untouched) and my spotify app says i cant connect to it

**Comment by spocon** [comment]
Are you in the same wifi / network ? I would need more input. Please provide stacktrace : journalctl -u lovspotify

**Comment by unbeeyt** [comment]
> Are you in the same wifi / network ? I would need more input. Please provide stacktrace : journalctl -u lovspotify

ok just let me reinstall the programm again cause i have my os reinstalled cause there was a lot of junk installed
