### ISSUE TITLE
Spotify not connected

### ISSUE THREAD

**Issue by KebabMasquay** [spocon/lovspotify#6]
Hi,

I'd like to use you tool but I think there's a authentication issue. I'm not sure but with this config file, it shows me "Spotify not connected " in the GUI.

Hope you can help me,
Thanks.
![image](https://user-images.githubusercontent.com/21956937/80424969-0c16dc80-88e3-11ea-906d-bf2e01c00127.png)

**Comment by spocon** [comment]
Hej, KebabMasquay , 

you usually don't have to change the configuration. Any Spotify Client , either on the phone or laptop  / tablet should find Lovspotify if its in the same network. 

After releasing the latest version of the underlying library of librespot-core we experience problems that the app doesnt show up in the spotify list of other clients. Let me come back to you.

Will write back when its fixed

**Comment by spocon** [comment]
hej KebabMasquay , 

The current version is working well , the issue happend in my network. So you should be able to connect to your Lovsportify through either your spotify on your phone or your laptop

REQUIREMENT: You need to be in the same network / router 

how to connect :

https://www.spotify.com/connect/
