### ISSUE TITLE
Multiple instances of music can play

### ISSUE THREAD

**Issue by chalkyjoe** [spocon/lovspotify#7]
Repro steps:

Play music from one device(A) -> the artist will appear on the screen, and can be controlled.
Pause A
Use another device(B) to connect -> the display will still show A, but B will play. If play is pressed on screen, A and B will play.

This seems to be intermittent, and I think there's a deeper problem causing this, as sometimes Spotify will disconnect, but the screen won't update to mirror this. Or once connecting, the screen will go from the previous session to "Spotify is not connected".

**Comment by spocon** [comment]
I will look into it but that seems more like either the backend system or spotify itself is the problem, because the javascript is just responding from the input which comes from the core system librespot-java

**Comment by chalkyjoe** [comment]
I think this has been fixed since the recent librespot-java update. Not had the issue since, and noticed something relating to multiple instances on the changelog:

- Avoid establishing two connections (afc7dc3)
